swagger: '2.0'
info:
  description: |
    This is a description of my wine shop API.
  version: 1.0.0
  title: Wine shop API
  contact:
    email: andslobby@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: products
  description: Everything about products
  externalDocs:
    description: Find out more
    url: https://github.com/slobby/shop-be
# schemes:
# - http
paths:
  /products:
    get:
      tags:
      - products
      summary: Finds all products
      description: Finds all products
      operationId: getAllProducts
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        500:
          description: Server error
  /products/{productId}:
    get:
      tags:
      - products
      summary: Find the product by id
      operationId: getProductById
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        description: ID of product
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Product'
        400:
          description: Invalid ID supplied
        404:
          description: Product not found
definitions:
  Product:
    type: object
    properties:
      id:
        type: string
        format: uuid
      title:
        type: string
      description:
        type: string
      count:
        type: integer
        format: int32
      price:
        type: number
        format: decimal
      image:
        type: string
        format: url
    xml:
      name: Product
externalDocs:
  description: Find out more about project
  url: https://github.com/slobby/shop-be
# host: cqtw2x2oqd.execute-api.eu-west-1.amazonaws.com
# basePath: /dev
schemes:
 - https
 - http
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /andslobby/shop-be/1.0.0